# Generated by Django 3.2.8 on 2021-10-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('SITE', 'Site'), ('BLOG', 'BLOG')], default='SITE', max_length=10),
        ),
    ]
