# Generated by Django 3.2.8 on 2021-10-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('status', models.CharField(choices=[('SITE', 'Site'), ('GALLERY', 'GAllery'), ('KARUSEL', 'Karusel')], default='SITE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
