# Generated by Django 3.2.8 on 2021-10-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
